// AUTO_GENERATED BY TestGenerationTool 
// Test class for IsSorted Class
package junit.generate.test;

import static org.junit.Assert.*;

import CSseniorProject.IsSorted;
import java.lang.Object;
import java.lang.String;
import java.util.Arrays;
import java.util.List;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

@RunWith(Parameterized.class)
public class IsSortedTest {
  private final String str0;

  private final Object ObjectExpectedForisSorted;

  public IsSorted ıssorted;

  public IsSortedTest(String str0, Object ObjectExpectedForisSorted) {
    this.str0 = str0;
        this.ObjectExpectedForisSorted = ObjectExpectedForisSorted;
        ;
  }

  @Before
  public void initialize() {
    ıssorted = new IsSorted();
  }

  @Parameterized.Parameters
  public static List dataForParameterized() {
    return Arrays.asList( new Object[][] {{"6", true} , {"aa", true} , {"bgm", true} , {"8icq", false} , {"852Pv", false} , {"Lui08c", false} , {"qT65cet", false} , {"HX27VGYO", false} , {"iTBRq250k", false} , {"YlsCgF6rAN", false} , {"dfw335s", false} , {"3OctThpT9w", false} , {"mAidjLAc12", false} , {"sK1FyP3Fzp", false} , {"H0AdEzRjdr", false} , {"6cszLpNYg8", false} , {"Kl5JPe7Qsa", false} , {"V55vlqLdcN", false} , {"3CZkkdKKkR", false} , {"k9xMH1yapI6", false} , {"EHcPb4t", false} , {"6S6Mihb", false} , {"h9OEUd6", false} , {"uycUUIw", false} , {"XkxE5Vl", false} , {"ePvaQep", false} , {"xtjMok1", false} , {"7NayXdV", false} , {"CemSFEc", false} , {"RtF03vF", false} , {"MKa", false} , {"aWi", false} , {"Iq1", false} , {"cJt", false} , {"gEs", false} , {"CYq", true} , {"5LE", false} , {"uBq", false} , {"aKA", false} , {"m4L", false} , {"L8", false} , {"TB", false} , {"aY", false} , {"uB", false} , {"rx", true} , {"QG", false} , {"MH", false} , {"H0", false} , {"6l", true} , {"t1", false}});
  }

  @Test
  public final void testİsSorted() {
    assertEquals(ObjectExpectedForisSorted, ıssorted.isSorted(str0));
  }
}
