// AUTO_GENERATED BY TestGenerationTool 
// Test class for HourlyEmployee Class
package junit.generate.test;

import static org.junit.Assert.*;

import CSseniorProject.HourlyEmployee;

import java.util.Arrays;
import java.util.List;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

@RunWith(Parameterized.class)
public class HourlyEmployeeTest {
  private final int int0;

  private final double DoubleExpectedForGetSalaryNew;

  private final double DoubleExpectedForGetSalary;

  public HourlyEmployee hourlyemployee;

  public HourlyEmployeeTest(int int0, double DoubleExpectedForGetSalaryNew,
      double DoubleExpectedForGetSalary) {
    this.int0 = int0;
        this.DoubleExpectedForGetSalaryNew = DoubleExpectedForGetSalaryNew;
        this.DoubleExpectedForGetSalary = DoubleExpectedForGetSalary;
        ;
  }

  @Before
  public void initialize() {
    hourlyemployee = new HourlyEmployee();
  }

  @Parameterized.Parameters
  public static List dataForParameterized() {
    return Arrays.asList( new Object[][] {{26867, 1225135.2, 547.2} , {96282, 4390459.2, 547.2} , {58198, 2653828.8000000003, 547.2} , {71283, 3250504.8000000003, 547.2} , {33624, 1533254.4000000001, 547.2} , {79874, 3642254.4, 547.2} , {12894, 587966.4, 547.2} , {99251, 4525845.600000001, 547.2} , {36519, 1665266.4000000001, 547.2} , {35628, 1624636.8, 547.2} , {28957, 1320439.2, 547.2} , {0, 0.0, 547.2} , {68042, 3102715.2, 547.2} , {48446, 2209137.6, 547.2} , {83548, 3809788.8000000003, 547.2} , {6150, 280440.0, 547.2} , {1, 45.6, 547.2} , {37919, 1729106.4000000001, 547.2} , {23134, 1054910.4000000001, 547.2} , {78339, 3572258.4, 547.2} , {98975, 4513260.0, 547.2} , {68638, 3129892.8000000003, 547.2} , {55883, 2548264.8000000003, 547.2} , {283, 12904.800000000001, 547.2} , {11853, 540496.8, 547.2} , {27270, 1243512.0, 547.2} , {8218, 374740.8, 547.2} , {4154, 189422.4, 547.2} , {24114, 1099598.4000000001, 547.2} , {23812, 1085827.2, 547.2} , {76024, 3466694.4, 547.2} , {80901, 3689085.6, 547.2} , {3739, 170498.4, 547.2} , {9637, 439447.2, 547.2} , {89425, 4077780.0, 547.2} , {35128, 1601836.8, 547.2} , {32678, 1490116.8, 547.2} , {78979, 3601442.4, 547.2} , {3971, 181077.6, 547.2} , {61768, 2816620.8000000003, 547.2} , {3102, 141451.2, 547.2} , {54323, 2477128.8000000003, 547.2} , {75464, 3441158.4, 547.2} , {31838, 1451812.8, 547.2} , {64649, 2947994.4, 547.2} , {38009, 1733210.4000000001, 547.2} , {68874, 3140654.4, 547.2} , {10271, 468357.60000000003, 547.2} , {876, 39945.6, 547.2} , {53412, 2435587.2, 547.2}});
  }

  @Test
  public final void testGetSalaryNew() {
    assertEquals(DoubleExpectedForGetSalaryNew, hourlyemployee.getSalaryNew(int0));
  }

  @Test
  public final void testGetSalary() {
    assertEquals(DoubleExpectedForGetSalary, hourlyemployee.getSalary());
  }
}
