// AUTO_GENERATED BY TestGenerationTool 
// Test class for Recognizer Class
package junit.generate.test;

import static org.junit.Assert.*;

import CSseniorProject.Recognizer;
import java.lang.String;
import java.util.Arrays;
import java.util.List;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

@RunWith(Parameterized.class)
public class RecognizerTest {
  private final String str0;

  private final String StringExpectedForconvert;

  public Recognizer recognizer;

  public RecognizerTest(String str0, String StringExpectedForconvert) {
    this.str0 = str0;
        this.StringExpectedForconvert = StringExpectedForconvert;
        ;
  }

  @Before
  public void initialize() {
    recognizer = new Recognizer();
  }

  @Parameterized.Parameters
  public static List dataForParameterized() {
    return Arrays.asList( new Object[][] {{"6", "?"} , {"aa", "?"} , {"bgm", "?"} , {"8icq", "?"} , {"852Pv", "?"} , {"Lui08c", "?"} , {"qT65cet", "?"} , {"HX27VGYO", "?"} , {"iTBRq250k", "?"} , {"YlsCgF6rAN", "?"} , {"dfw335s", "?"} , {"3OctThpT9w", "?"} , {"mAidjLAc12", "?"} , {"sK1FyP3Fzp", "?"} , {"H0AdEzRjdr", "?"} , {"6cszLpNYg8", "?"} , {"Kl5JPe7Qsa", "?"} , {"V55vlqLdcN", "?"} , {"3CZkkdKKkR", "?"} , {"k9xMH1yapI6", "?"} , {"EHcPb4t", "?"} , {"6S6Mihb", "?"} , {"h9OEUd6", "?"} , {"uycUUIw", "?"} , {"XkxE5Vl", "?"} , {"ePvaQep", "?"} , {"xtjMok1", "?"} , {"7NayXdV", "?"} , {"CemSFEc", "?"} , {"RtF03vF", "?"} , {"MKa", "?"} , {"aWi", "?"} , {"Iq1", "?"} , {"cJt", "?"} , {"gEs", "?"} , {"CYq", "?"} , {"5LE", "?"} , {"uBq", "?"} , {"aKA", "?"} , {"m4L", "?"} , {"L8", "?"} , {"TB", "?"} , {"aY", "?"} , {"uB", "?"} , {"rx", "?"} , {"QG", "?"} , {"MH", "?"} , {"H0", "?"} , {"6l", "?"} , {"t1", "?"}});
  }

  @Test
  public final void testConvert() {
    assertEquals(StringExpectedForconvert, recognizer.convert(str0));
  }
}
