// AUTO_GENERATED BY TestGenerationTool 
// Test class for SalariedEmployee Class
package junit.generate.test;

import static org.junit.Assert.*;

import CSseniorProject.SalariedEmployee;

import java.util.Arrays;
import java.util.List;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

@RunWith(Parameterized.class)
public class SalariedEmployeeTest {
  private final double DoubleExpectedForGetSalary;

  public SalariedEmployee salariedemployee;

  public SalariedEmployeeTest(double DoubleExpectedForGetSalary) {
    this.DoubleExpectedForGetSalary = DoubleExpectedForGetSalary;
        ;
  }

  @Before
  public void initialize() {
    salariedemployee = new SalariedEmployee();
  }

  @Parameterized.Parameters
  public static List dataForParameterized() {
    return Arrays.asList( new Object[][] {{10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23} , {10435.23}});
  }

  @Test
  public final void testGetSalary() {
    assertEquals(DoubleExpectedForGetSalary, salariedemployee.getSalary());
  }
}
