// AUTO_GENERATED BY TestGenerationTool 
// Test class for Math Class
package junit.generate.test;

import static org.junit.Assert.*;

import CSseniorProject.Math;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.String;
import java.util.Arrays;
import java.util.List;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

@RunWith(Parameterized.class)
public class MathTest {
  private final int int0;

  private final int int1;

  private final int int2;

  private final int int3;

  private final String str0;

  private final String str1;

  private final String str2;

  private final String str3;

  private final String str4;

  private final boolean boolean0;

  private final String StringExpectedFormethodSt;

  private final Boolean BooleanExpectedForbol;

  private final Boolean BooleanExpectedForvalidate;

  private final int intExpectedFormm;

  private final String StringExpectedForstr;

  private final int intExpectedForm1;

  private final int intExpectedForm2;

  private final Object ObjectExpectedForm3;

  public Math math;

  public MathTest(int int0, int int1, int int2, int int3, String str0, String str1, String str2,
      String str3, String str4, Boolean boolean0, String StringExpectedFormethodSt,
      Boolean BooleanExpectedForbol, Boolean BooleanExpectedForvalidate, int intExpectedFormm,
      String StringExpectedForstr, int intExpectedForm1, int intExpectedForm2,
      Object ObjectExpectedForm3) {
    this.int0 = int0;
        this.int1 = int1;
        this.int2 = int2;
        this.int3 = int3;
        this.str0 = str0;
        this.str1 = str1;
        this.str2 = str2;
        this.str3 = str3;
        this.str4 = str4;
        this.boolean0 = boolean0;
        this.StringExpectedFormethodSt = StringExpectedFormethodSt;
        this.BooleanExpectedForbol = BooleanExpectedForbol;
        this.BooleanExpectedForvalidate = BooleanExpectedForvalidate;
        this.intExpectedFormm = intExpectedFormm;
        this.StringExpectedForstr = StringExpectedForstr;
        this.intExpectedForm1 = intExpectedForm1;
        this.intExpectedForm2 = intExpectedForm2;
        this.ObjectExpectedForm3 = ObjectExpectedForm3;
        ;
  }

  @Before
  public void initialize() {
    math = new Math();
  }

  @Parameterized.Parameters
  public static List dataForParameterized() {
    return Arrays.asList( new Object[][] {{70318, 70318, 70318, 70318, "6", "6", "6", "6", "6", false, "670318670318", true, false, 0, "6", 70318, 1, "6"} , {639011, 639011, 639011, 639011, "''", "''", "''", "''", "''", true, "''639011''639011", true, true, 0, "''", 639011, 1, "''"} , {843, 843, 843, 843, "bgm", "bgm", "bgm", "bgm", "bgm", true, "bgm843bgm843", true, false, 0, "bgm", 843, 1, "bgm"} , {112, 112, 112, 112, "8icq", "8icq", "8icq", "8icq", "8icq", false, "8icq1128icq112", true, false, 0, "8icq", 112, 1, "8icq"} , {949857, 949857, 949857, 949857, "852Pv", "852Pv", "852Pv", "852Pv", "852Pv", true, "852Pv949857852Pv949857", true, false, 0, "852Pv", 949857, 1, "852Pv"} , {8680814, 8680814, 8680814, 8680814, "Lui08c", "Lui08c", "Lui08c", "Lui08c", "Lui08c", true, "Lui08c8680814Lui08c8680814", true, false, 0, "Lui08c", 8680814, 1, "Lui08c"} , {2854, 2854, 2854, 2854, "qT65cet", "qT65cet", "qT65cet", "qT65cet", "qT65cet", false, "qT65cet2854qT65cet2854", true, false, 0, "qT65cet", 2854, 1, "qT65cet"} , {0, 0, 0, 0, "HX27VGYO", "HX27VGYO", "HX27VGYO", "HX27VGYO", "HX27VGYO", false, "HX27VGYO0HX27VGYO0", true, true, 0, "HX27VGYO", 0, 1, "HX27VGYO"} , {95952, 95952, 95952, 95952, "iTBRq250k", "iTBRq250k", "iTBRq250k", "iTBRq250k", "iTBRq250k", false, "iTBRq250k95952iTBRq250k95952", true, false, 0, "iTBRq250k", 95952, 1, "iTBRq250k"} , {81668, 81668, 81668, 81668, "YlsCgF6rAN", "YlsCgF6rAN", "YlsCgF6rAN", "YlsCgF6rAN", "YlsCgF6rAN", true, "YlsCgF6rAN81668YlsCgF6rAN81668", true, false, 0, "YlsCgF6rAN", 81668, 1, "YlsCgF6rAN"} , {453, 453, 453, 453, "dfw335s", "dfw335s", "dfw335s", "dfw335s", "dfw335s", false, "dfw335s453dfw335s453", true, false, 0, "dfw335s", 453, 1, "dfw335s"}});
  }

  @Test
  public final void testMethodSt() {
    assertEquals(StringExpectedFormethodSt, math.methodSt(str0, int0, str1, int1));
  }

  @Test
  public final void testBol() {
    assertEquals(BooleanExpectedForbol, math.bol(boolean0));
  }

  @Test
  public final void testValidate() {
    assertEquals(BooleanExpectedForvalidate, math.validate(int0));
  }

  @Test
  public final void testMm() {
    assertEquals(intExpectedFormm, math.mm());
  }

  @Test
  public final void testStr() {
    assertEquals(StringExpectedForstr, math.str(str0));
  }

  @Test
  public final void testM1() {
    assertEquals(intExpectedForm1, math.m1(str0, int0));
  }

  @Test
  public final void testM2() {
    assertEquals(intExpectedForm2, math.m2());
  }

  @Test
  public final void testM3() {
    assertEquals(ObjectExpectedForm3, math.m3(str0));
  }
}
