// AUTO_GENERATED BY TestGenerationTool 
// Test class for GetDigit Class
package junit.generate.test;

import static org.junit.Assert.*;

import CSseniorProject.GetDigit;

import java.util.Arrays;
import java.util.List;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

@RunWith(Parameterized.class)
public class GetDigitTest {
  private final int int0;

  private final int int1;

  private final int intExpectedForgetDigit;

  public GetDigit getdigit;

  public GetDigitTest(int int0, int int1, int intExpectedForgetDigit) {
    this.int0 = int0;
        this.int1 = int1;
        this.intExpectedForgetDigit = intExpectedForgetDigit;
        ;
  }

  @Before
  public void initialize() {
    getdigit = new GetDigit();
  }

  @Parameterized.Parameters
  public static List dataForParameterized() {
    return Arrays.asList( new Object[][] {{26867, 26867, 0} , {96282, 96282, 0} , {58198, 58198, 0} , {71283, 71283, 0} , {33624, 33624, 0} , {79874, 79874, 0} , {12894, 12894, 1} , {99251, 99251, 0} , {36519, 36519, 0} , {35628, 35628, 0} , {28957, 28957, 0} , {0, 0, 0} , {68042, 68042, 0} , {48446, 48446, 0} , {83548, 83548, 0} , {6150, 6150, 0} , {1, 1, 1} , {37919, 37919, 0} , {23134, 23134, 0} , {78339, 78339, 0} , {98975, 98975, 0} , {68638, 68638, 0} , {55883, 55883, 0} , {283, 283, 0} , {11853, 11853, 1} , {27270, 27270, 0} , {8218, 8218, 0} , {4154, 4154, 0} , {24114, 24114, 0} , {23812, 23812, 0} , {76024, 76024, 0} , {80901, 80901, 0} , {3739, 3739, 0} , {9637, 9637, 0} , {89425, 89425, 0} , {35128, 35128, 0} , {32678, 32678, 0} , {78979, 78979, 0} , {3971, 3971, 0} , {61768, 61768, 0} , {3102, 3102, 0} , {54323, 54323, 0} , {75464, 75464, 0} , {31838, 31838, 0} , {64649, 64649, 0} , {38009, 38009, 0} , {68874, 68874, 0} , {10271, 10271, 1} , {876, 876, 0} , {53412, 53412, 0}});
  }

  @Test
  public final void testGetDigit() {
    assertEquals(intExpectedForgetDigit, getdigit.getDigit(int0, int1));
  }
}
