// AUTO_GENERATED BY TestGenerationTool 
// Test class for Calculator Class
package junit.generate.test;

import static org.junit.Assert.*;

import cs401caseClasses.Calculator;
import org.junit.Test;

public class CalculatorTest {
  private Calculator calculator = new Calculator();

  @Test
  public final void testadd() {
    ınt actual = calculator.add([ınt value1, ınt value2]);
  }

  @Test
  public final void testsubtract() {
    ınt actual = calculator.subtract([ınt value1, ınt value2]);
  }

  @Test
  public final void testmultiply() {
    ınt actual = calculator.multiply([ınt value1, ınt value2]);
  }

  @Test
  public final void testdivide() {
    ınt actual = calculator.divide([ınt value1, ınt value2]);
  }
}
