// AUTO_GENERATED BY TestGenerationTool 
// Test class for Math Class
package junit.generate.test;

import static org.junit.Assert.*;

import cs401caseClasses.Math;
import org.junit.Test;

public class MathTest {
  private Math math = new Math();

  @Test
  public final void testvalidate() {
    Boolean actual = math.validate;
  }

  @Test
  public final void testprint() {
    void actual = math.print;
  }

  @Test
  public final void testemptyMethod() {
    void actual = math.emptyMethod;
  }

  @Test
  public final void teststr() {
    String actual = math.str;
  }

  @Test
  public final void testadd() {
    ınt actual = math.add;
  }
}
