// AUTO_GENERATED BY TestGenerationTool 
// Test class for MyList Class
package junit.generate.test;

import static org.junit.Assert.*;

import cs401caseClasses.MyList;
import org.junit.Test;

public class MyListTest {
  private MyList mylist = new MyList();

  @Test
  public final void testADD() {
     actual = mylist.add();
  }

  @Test
  public final void testREMOVE() {
     actual = mylist.remove();
  }

  @Test
  public final void testSİZE() {
    ınt actual = mylist.size();
  }

  @Test
  public final void testREMOVEALL() {
     actual = mylist.removeAll();
  }
}
