// AUTO_GENERATED BY TestGenerationTool 
// Test class for WithOneMethod Class
package junit.generate.test;

import static org.junit.Assert.*;

import cs401caseClasses.WithOneMethod;
import org.junit.Test;

public class WithOneMethodTest {
  private WithOneMethod withonemethod = new WithOneMethod();

  @Test
  public void testadd() {
  }
}
